### ISSUE TITLE
elo.run with multiple players specified by multiple columns.

### ISSUE THREAD

**Issue by SamEhrlich** [cran/elo#1]
I am looking to use the elo.run function to model a 5v5 game. I have a dataframe with all 10 playerids in seperate columns and a column for the outcome of the game. I am getting this error 

"Error in mtfrm.default(c("99322214618656216", "99322214241694525", "101389713973624205",  : 
  cannot mtfrm" 
  
  when attempting to input more than 2 players in the home or away team. My function currently looks like this 
  
  elo.run(home_team_win ~ players(playerid_1,playerid_2,playerid_3) + 
                        players(playerid_6,playerid_7,playerid_8),
                      data = test_players_run, k = 20)
                      
I have no problem when I only include 2 players in either home or away teams. Is there something that I can fix to allow for more than 2 players to be able to entered into the function? I tried looking through the github code, but there are so many functions within functions I am not sure where my error is coming from.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by SamEhrlich** [comment]
okay i will remove my comment. thank you gabor!

**Comment by gaborcsardi** [comment]
You can keep it, no worries. But if you want to reach the package authors, then see those fields.
